# Generated by Django 2.1.11 on 2020-09-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('questionId', models.IntegerField(verbose_name='关联问题id')),
                ('submitId', models.IntegerField(verbose_name='关联提交id')),
                ('wjId', models.IntegerField(verbose_name='问卷id')),
                ('type', models.CharField(max_length=20, verbose_name='题目类型')),
                ('answer', models.IntegerField(blank=True, null=True, verbose_name='答案')),
                ('answerText', models.TextField(blank=True, null=True, verbose_name='文本答案')),
            ],
            options={
                'verbose_name': '回答表',
                'verbose_name_plural': '回答表',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='选项名')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='题目标题')),
                ('type', models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '填空题')], default=1, verbose_name='题目类型')),
                ('must', models.BooleanField(verbose_name='是否必填')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
            },
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='个人邮箱')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('intention_position', models.CharField(help_text='请填写应聘职位', max_length=255, verbose_name='应聘职位')),
            ],
            options={
                'verbose_name': '答题人',
                'verbose_name_plural': '答题人',
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wjId', models.IntegerField(verbose_name='关联问卷id')),
                ('submitTime', models.DateTimeField(verbose_name='提交时间')),
                ('submitIp', models.CharField(max_length=15, verbose_name='提交ip')),
                ('useTime', models.IntegerField(verbose_name='填写用时')),
                ('submitUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents', verbose_name='提交人')),
            ],
            options={
                'verbose_name': '提交信息',
                'verbose_name_plural': '提交信息',
            },
        ),
        migrations.CreateModel(
            name='Wj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='试卷名')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='是否发布')),
                ('desc', models.TextField(null=True, verbose_name='问卷说明')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='wjId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj'),
        ),
        migrations.AddField(
            model_name='options',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Question', verbose_name='关联题目'),
        ),
    ]
