# Generated by Django 2.2.11 on 2020-09-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='动物名')),
            ],
            options={
                'verbose_name': '动物',
                'verbose_name_plural': '动物',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='选项名')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='个人邮箱')),
                ('phone', models.CharField(max_length=15, verbose_name='手机号')),
                ('intention_position', models.CharField(help_text='请填写应聘职位', max_length=255, verbose_name='应聘职位')),
            ],
            options={
                'verbose_name': '答题人',
                'verbose_name_plural': '答题人',
            },
        ),
        migrations.CreateModel(
            name='Wj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='试卷名')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='是否发布')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='问卷说明')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='性格别名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='主要表现')),
                ('professional', models.TextField(blank=True, null=True, verbose_name='代表职业')),
                ('animal', models.OneToOneField(blank=True, help_text='仅PDP性格测试需要选择', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Animal', verbose_name='动物')),
                ('wj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '性格分析',
                'verbose_name_plural': '性格分析',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submit_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='提交人IP')),
                ('use_time', models.IntegerField(blank=True, null=True, verbose_name='答题耗时')),
                ('answer_choice', models.CharField(blank=True, max_length=255, null=True, verbose_name='选择题答案')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='主观题答案')),
                ('submit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents', verbose_name='提交人')),
                ('wj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qid', models.IntegerField(null=True, verbose_name='题目序号')),
                ('title', models.CharField(max_length=100, verbose_name='题目标题')),
                ('type', models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '主观题')], default=1, verbose_name='题目类型')),
                ('must', models.BooleanField(verbose_name='是否必填')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Animal', verbose_name='动物')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('options', models.ManyToManyField(to='recruit.Options', verbose_name='选项')),
                ('wjId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='所属问卷')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'unique_together': {('qid', 'wjId')},
            },
        ),
    ]
