# Generated by Django 2.0.13 on 2020-10-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='文件名')),
                ('tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型标记')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('wj_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='试卷名称')),
            ],
            options={
                'verbose_name': '性格分析资料',
                'verbose_name_plural': '性格分析资料',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='性格别名')),
                ('wj', models.CharField(blank=True, max_length=200, null=True, verbose_name='试卷名称')),
                ('feature', models.TextField(null=True, verbose_name='性格特征')),
            ],
            options={
                'verbose_name': '性格别名',
                'verbose_name_plural': '性格别名',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submit_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='提交人IP')),
                ('use_time', models.IntegerField(blank=True, null=True, verbose_name='答题耗时')),
                ('answer_choice', models.TextField(blank=True, null=True, verbose_name='选择题答案')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='主观题答案')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='主要表现')),
                ('professional', models.TextField(blank=True, null=True, verbose_name='代表职业')),
                ('wj', models.CharField(blank=True, max_length=255, null=True, verbose_name='试卷名称')),
                ('animal', models.OneToOneField(blank=True, help_text='仅PDP性格测试需要选择', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Animal', verbose_name='性格别名')),
            ],
            options={
                'verbose_name': '性格分析',
                'verbose_name_plural': '性格分析',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='选项名')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qid', models.IntegerField(null=True, verbose_name='题目序号')),
                ('title', models.CharField(max_length=100, verbose_name='题目标题')),
                ('type', models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '主观题')], default=1, verbose_name='题目类型')),
                ('wj_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='试卷名称')),
                ('must', models.BooleanField(verbose_name='是否必填')),
                ('options', models.TextField(blank=True, help_text='多个选项之间用"|"隔开', null=True, verbose_name='选项')),
                ('create_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('animal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='动物')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('respondenter_name', models.CharField(max_length=100, verbose_name='应聘者姓名')),
                ('result', models.TextField(blank=True, null=True, verbose_name='最终报告')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruit.Answer', verbose_name='答卷')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
            },
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='个人邮箱')),
                ('phone', models.CharField(max_length=15, verbose_name='手机号')),
                ('intention_position', models.CharField(help_text='请填写应聘职位', max_length=255, verbose_name='应聘职位')),
            ],
            options={
                'verbose_name': '答题人',
                'verbose_name_plural': '答题人',
            },
        ),
        migrations.CreateModel(
            name='RespondentToken',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='key')),
                ('status', models.BooleanField(default=False, help_text='0:未过期, 1:过期', verbose_name='是否过期')),
                ('respondents', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents')),
            ],
            options={
                'verbose_name': 'Respondent Token',
                'verbose_name_plural': 'Respondent Token',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='excel_data')),
                ('status', models.IntegerField(choices=[(1, '存在'), (2, '已删除')], default=1, verbose_name='文档是否存在')),
                ('create_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '批量添加试题',
                'verbose_name_plural': '批量添加试题',
            },
        ),
        migrations.CreateModel(
            name='Wj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='试卷名称')),
                ('wj_alias', models.CharField(max_length=255, null=True, unique=True, verbose_name='试卷别名')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='是否发布')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='问卷说明')),
                ('create_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('type', models.IntegerField(null=True, verbose_name='分析类型')),
                ('max_quiz_time', models.CharField(default=3600, max_length=10, verbose_name='最大答题时间/秒')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('qid', 'wj_name')},
        ),
        migrations.AddField(
            model_name='answer',
            name='submit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents', verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='answer',
            name='wj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='问卷'),
        ),
    ]
