# Generated by Django 2.2.11 on 2020-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondents',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='手机号'),
        ),
    ]
