# Generated by Django 2.2.11 on 2020-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wj',
            name='type',
            field=models.IntegerField(null=True, verbose_name='分析类型'),
        ),
    ]
