# Generated by Django 2.0.13 on 2020-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wj',
            name='status',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, help_text='0:未发布, 1:已发布', verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='wj',
            name='type',
            field=models.IntegerField(help_text='1:PDF性格测试, 2:霍兰德职业测试', null=True, verbose_name='分析类型'),
        ),
    ]
