# Generated by Django 2.2.11 on 2020-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20200923_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='questionId',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='recruit.Options', verbose_name='关联题目'),
        ),
    ]
