# Generated by Django 2.2.11 on 2020-09-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_wj_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '性格分析资料',
                'verbose_name_plural': '性格分析资料',
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': '性格别名', 'verbose_name_plural': '性格别名'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='alias',
        ),
        migrations.AddField(
            model_name='animal',
            name='wj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='问卷'),
        ),
    ]
