# Generated by Django 2.2.11 on 2020-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20200923_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='recruit.Options', verbose_name='选项'),
        ),
    ]
