# Generated by Django 2.2.11 on 2020-09-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20200923_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBelongsToAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='动物名')),
            ],
            options={
                'verbose_name': '公共字段序列',
                'db_table': 'BaseTable',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.IntegerField(null=True, unique=True, verbose_name='题目序号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '主观题')], default=1, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='question',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.QuestionBelongsToAnimal'),
        ),
    ]
