# Generated by Django 2.2.11 on 2020-09-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20200928_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='animal',
            field=models.OneToOneField(blank=True, help_text='仅PDP性格测试需要选择', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Animal', verbose_name='性格别名'),
        ),
    ]
