# Generated by Django 2.2.11 on 2020-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20200928_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='tags',
            field=models.ManyToManyField(null=True, to='recruit.Animal', verbose_name='标记'),
        ),
    ]
