# Generated by Django 2.2.11 on 2020-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20200928_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='wj',
            field=models.ManyToManyField(blank=True, null=True, to='recruit.Wj', verbose_name='试卷'),
        ),
    ]
