# Generated by Django 2.2.11 on 2020-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20200923_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': '动物', 'verbose_name_plural': '动物'},
        ),
        migrations.AlterModelTable(
            name='animal',
            table=None,
        ),
    ]
