# Generated by Django 2.2.11 on 2020-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20200923_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='题目序号'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('qid', 'wjId')},
        ),
    ]
