# Generated by Django 2.2.11 on 2020-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_analysisdata_wj'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='feature',
            field=models.TextField(null=True, verbose_name='性格特征'),
        ),
    ]
