# Generated by Django 2.1.11 on 2020-09-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_animal_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('result', models.TextField(blank=True, null=True, verbose_name='最终报告')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruit.Answer', verbose_name='答卷')),
                ('respondenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents', verbose_name='答题者')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
            },
        ),
    ]
