# Generated by Django 2.2.11 on 2020-09-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20200923_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '答卷', 'verbose_name_plural': '答卷'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerText',
            field=models.TextField(blank=True, null=True, verbose_name='主观题答案'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='性格别名')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='性格别名')),
                ('content', models.TextField(verbose_name='主要表现')),
                ('professional', models.TextField(blank=True, null=True, verbose_name='代表职业')),
                ('wj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Wj', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '性格分析',
                'verbose_name_plural': '性格分析',
            },
        ),
    ]
