# Generated by Django 2.1.11 on 2020-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata',
            name='tags',
            field=models.ManyToManyField(to='recruit.Animal', verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='wj',
            field=models.ManyToManyField(to='recruit.Wj', verbose_name='试卷'),
        ),
    ]
