# Generated by Django 2.2.11 on 2020-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20200923_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='主要表现'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
    ]
