# Generated by Django 2.0.13 on 2020-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_auto_20200930_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_choice',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='选择题答案'),
        ),
    ]
