# Generated by Django 2.2.11 on 2020-09-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_character_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answerChoice',
            new_name='answer_choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answerText',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='submitIp',
            new_name='submit_ip',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='submitUser',
            new_name='submit_user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='useTime',
            new_name='use_time',
        ),
        migrations.AlterField(
            model_name='character',
            name='animal',
            field=models.OneToOneField(blank=True, help_text='仅PDP性格测试需要选择', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Animal', verbose_name='动物'),
        ),
    ]
