# Generated by Django 2.0.13 on 2020-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_auto_20201014_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='status',
            field=models.IntegerField(choices=[(1, '存在'), (2, '已删除')], default=1, verbose_name='文档是否存在'),
        ),
    ]
