# Generated by Django 2.0.13 on 2020-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_uploadfile_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wj',
            name='wj_alias',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='试卷别名'),
        ),
    ]
