# Generated by Django 2.0.13 on 2020-10-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0015_wj_wj_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('expiration_time', models.IntegerField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': 'Respondent Token',
                'verbose_name_plural': 'Respondent Token',
            },
        ),
        migrations.AddField(
            model_name='respondents',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.RespondentToken'),
        ),
    ]
