# Generated by Django 2.0.13 on 2020-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_auto_20201019_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondenttoken',
            name='expiration_time',
            field=models.IntegerField(default=3600, verbose_name='过期时间'),
        ),
    ]
