# Generated by Django 2.0.13 on 2020-10-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_auto_20201019_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondents',
            name='token',
        ),
        migrations.AddField(
            model_name='respondenttoken',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Respondents'),
        ),
    ]
