# Generated by Django 2.0.13 on 2020-10-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_auto_20201019_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondenttoken',
            old_name='token',
            new_name='respondentor',
        ),
    ]
