# Generated by Django 2.0.13 on 2020-10-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0019_auto_20201019_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondenttoken',
            old_name='respondentor',
            new_name='respondents',
        ),
    ]
