# Generated by Django 2.0.13 on 2020-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_auto_20201021_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondenttoken',
            name='expiration_time',
        ),
        migrations.AlterField(
            model_name='respondenttoken',
            name='key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='key'),
        ),
    ]
