# Generated by Django 2.0.13 on 2020-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0022_auto_20201021_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='wj',
            name='max_quiz_time',
            field=models.CharField(default=3600, max_length=10, verbose_name='最大答题时间'),
        ),
    ]
