# Generated by Django 2.0.13 on 2020-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_wj_max_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wj',
            name='max_quiz_time',
            field=models.CharField(default=3600, max_length=10, verbose_name='最大答题时间/秒'),
        ),
    ]
