# Generated by Django 2.0.13 on 2020-10-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0024_auto_20201021_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenttoken',
            name='status',
            field=models.BooleanField(default=False, help_text='0:未过期, 1:过期', verbose_name='是否过期'),
        ),
    ]
